//
//  MenuRouter.swift
//  RentBike
//
//  Created by Evgeny Ivanov on 22.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuRoutingLogic {
    func openRide()
    func openWallet()
    func openPromo()
}

protocol MenuDataPassing {
    var dataStore: MenuDataStore? { get }
}

class MenuRouter: MenuRoutingLogic, MenuDataPassing {
    weak var viewController: MenuViewController!
    var dataStore: MenuDataStore?

    // MARK: Routing

    func openRide() {
        let flow = MenuFlow()
        flow.rides(from: viewController)
    }
    func openWallet() {
        let flow = MenuFlow()
        flow.wallet(from: viewController)
    }
    func openPromo() {
        let flow = MenuFlow()
        flow.promo(from: viewController)
    }
}
