//
//  MenuPresenter.swift
//  RentBike
//
//  Created by Evgeny Ivanov on 22.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuPresentationLogic {
    
}

class MenuPresenter: MenuPresentationLogic {
    weak var viewController: MenuDisplayLogic?

    // MARK: Do something
    
}
